/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aulagradle;

class AppTest {
     public void testApp(){
         asserttrue(true);
    }

    private void asserttrue(boolean b) {
    }
}
